import { Canvas } from '@react-three/fiber'
import Head from 'next/head'
import Image from 'next/image'
import Orbit from '../components/Orbit'
import Skybox from '../components/Skybox'
import Todo from '../components/Todo/Todo'
import Todos from '../components/Todo/Todos'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Hive</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <div className='w-full h-[100vh]'>
        <Canvas>
          
          <Skybox />
          <Todo />
          <Orbit />
        </Canvas>
      </div>
    </>
  )
}
