import { Canvas } from '@react-three/fiber'
import Head from 'next/head'
import Image from 'next/image'
import Calendar from '../components/Calendar/Calendar'
import Call from '../components/Call'
import Email from '../components/Email/Email'
import Github from '../components/Github/Github'
import ChatWindow from '../components/Message/Message'
import Player from '../components/Music/Player'
import Notion from '../components/Notion'
import Orbit from '../components/Orbit'
import Skybox from '../components/Skybox'
import ThreeDText from '../components/Todo/ThreeDText'
import Todo from '../components/Todo/Todo'
import Todos from '../components/Todo/Todos'
import Twitter from '../components/Twitter/Twitter'
import VideoCall from '../components/VideoCall'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Hive</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <div className='w-full h-[100vh]'>
        <Canvas>
          
          <Skybox />
          {/* <ThreeDText /> */}
          
          <Twitter />
          <Todo />
          <Github />
          <Email />
          <Player />
          <Calendar />
          <ChatWindow />
          <VideoCall />
          <Notion />
          {/* <Call  /> */}
          <Orbit />
        </Canvas>
      </div>
    </>
  )
}
